## LIMBO Instrumentation
* requirements:
    * mlib_devel : [m2019a branch](https://github.com/casper-astro/mlib_devel/tree/a6a1e4767340ff2a0f7856b1a0c7a1f3a582e4fc)
    * casperfpga : [py38 branch](https://github.com/liuweiseu/casperfpga/commits/py38)

### Step0: Import necessary packages

In [22]:
import os
import sys
import casperfpga
import logging
import time
import redis
import numpy as np
import struct

### Step1: Set parameters

In [29]:
'''
SNAP board info
'''
snap_ip  = '192.168.2.100'
port    = 69

fpg_file='snap_adc_2023-04-14_2313.fpg'
#fpg_file = 'snap_adc_2023-04-15_1004.fpg'
'''
Parameters for spectrameter
''' 
# sample freq
fs = 500
#fs = 1000
adc_ref = 10
# adc gain: it's voltage multplier inside the ADC IC.
adc_gain = 4



### Step2: Connect to the SNAP board 

In [30]:
logger=logging.getLogger('snap')
logging.basicConfig(filename='snap.log',level=logging.DEBUG)
snap=casperfpga.CasperFpga(snap_ip, port, logger=logger)

ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f2e3a946340>>, <Future finished exception=KatcpClientError("Failed to connect to ('192.168.2.100', 69)")>)
Traceback (most recent call last):
  File "/home/wei/.conda/envs/py38/lib/python3.8/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/wei/.conda/envs/py38/lib/python3.8/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/home/wei/.conda/envs/py38/lib/python3.8/site-packages/tornado/gen.py", line 782, in run
    yielded = self.gen.send(value)
  File "/home/wei/.conda/envs/py38/lib/python3.8/site-packages/katcp/client.py", line 682, in _install
    raise KatcpClientError("Failed to connect to {0!r}"
katcp.core.KatcpClientError: Failed to connect to ('192.168.2.100', 69)


### Step4: Upload fpg file

In [31]:
fpg = '../fpg/'+fpg_file
print('fpg file: ',fpg)
snap.upload_to_ram_and_program(fpg)
# We should get system info in "upload_to_ran_and_program", but it seems there are some issues in the casperfpga
snap.get_system_information(fpg,initialise_objects=False)

fpg file:  ../fpg/snap_adc_2023-04-14_2313.fpg


100% (103 of 103) |######################| Elapsed Time: 0:01:44 Time:  0:01:44


### Step5: Init clk and adc

In [69]:
# numChannel depends on fs
if(fs==1000):
    numChannel = 1
    inputs = [1,1,1,1]
elif(fs==500):
    numChannel = 2
    inputs = [1,1,3,3]
# init adc and clk
adc=snap.adcs['snap_adc']
adc.ref = adc_ref
adc.selectADC()
adc.init(sample_rate=fs,numChannel=numChannel)
adc.rampTest(retry=True)
adc.adc.selectInput(inputs)
adc.selectADC()
adc.set_gain(adc_gain)

File in flash is:  snap_adc_2023-04-14_2313.fpg


In [70]:
snap.listdev()

['adc16_controller',
 'adc16_use_synth',
 'adc16_wb_ram0',
 'adc16_wb_ram1',
 'adc16_wb_ram2',
 'adc_snap_bram',
 'adc_snap_ctrl',
 'adc_snap_status',
 'adc_trig',
 'led_ctrl',
 'lmx_ctrl',
 'sys',
 'sys_board_id',
 'sys_clkcounter',
 'sys_rev',
 'sys_rev_rcs',
 'sys_scratchpad',
 'ten_gbe']

In [28]:
snap.registers

['adc_snap_ctrl', 'adc_snap_status', 'adc_trig', 'led_ctrl', 'sys_board_id', 'sys_rev', 'sys_rev_rcs', 'sys_scratchpad', 'sys_clkcounter']

In [51]:
d=adc.readRAM()
print(type(d))

<class 'dict'>


In [52]:
d=np.array(d[1])

In [53]:
d.shape

(128, 8)

In [81]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)


[[1 2 3 4]
 [5 6 7 8]]


In [82]:
a=a[:,[3,2,1,0]]
print(a)

[[4 3 2 1]
 [8 7 6 5]]


In [83]:
a.reshape(4,2)

array([[4, 3],
       [2, 1],
       [8, 7],
       [6, 5]])

In [84]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])